server:
  port: ${SERVER_PORT:9000}
spring:
  application:
    name: techwikiplus-user
    version: ${IMAGE_TAG:LOCAL_VERSION}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:13306}/${MYSQL_DATABASE:techwikiplus-user}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&cachePrepStmts=true&useServerPrepStmts=true
    username: ${MYSQL_USER:techwikiplus}
    password: ${MYSQL_PASSWORD:techwikiplus}
    hikari:
      maximum-pool-size: 30 # 최대 커넥션 풀 크기
      minimum-idle: 10 # 최소 유휴 커넥션 수
      connection-timeout: 30000 # 커넥션 타임아웃 (30초)
      idle-timeout: 600000 # 유휴 커넥션 타임아웃 (10분)
      max-lifetime: 1800000 # 커넥션 최대 생명주기 (30분)
  jpa:
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:false}  # 성능 최적화를 위해 비활성화
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        # 배치 처리 설정
        jdbc:
          batch_size: 5000
          batch_versioned_data: true
          fetch_size: 1000
        # SQL 순서 최적화
        order_inserts: true
        order_updates: true
        # 통계 비활성화 (성능 향상)
        generate_statistics: false
        # 캐시 비활성화 (배치 처리에서는 불필요)
        cache:
          use_second_level_cache: false
          use_query_cache: false
        # 메타데이터 최적화
        # JDBC 메타데이터 접근 허용 (자동 dialect 감지를 위해 필요)
        boot:
          allow_jdbc_metadata_access: true
        # MySQL 8.x에 최적화된 Dialect 사용
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:16379}
      password: ${REDIS_PASSWORD:techwikiplus}
  # Mail configuration
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:11025}
    username: ${MAIL_USERNAME:noreply@techwikiplus.com}
    password: ${MAIL_PASSWORD:techwikiplus}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:false}
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
# Springdoc OpenAPI 설정
# REST Docs로 생성된 OpenAPI 문서를 Swagger UI로 표시
# API 문서 접근 경로:
# - OpenAPI YAML: http://localhost:9000/api-docs/openapi3.yml (REST Docs로 생성)
# - Swagger UI: http://localhost:9000/swagger-ui/index.html
springdoc:
  api-docs:
    enabled: true  # Swagger UI가 작동하려면 활성화 필요
  swagger-ui:
    enabled: true
    url: /api-docs/openapi3.yml  # REST Docs로 생성된 OpenAPI 문서 경로 지정

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-for-development-environment-only}
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY:3600}  # 1 hour
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY:2592000}  # 30 days
