# User Service 알람 규칙

groups:
  - name: user-service
    rules:
      # User Service 다운
      - alert: UserServiceDown
        expr: up{job="user-service"} == 0
        for: 5m
        labels:
          severity: critical
          service: user-service
        annotations:
          summary: "User Service is down"
          description: "User Service has been down for more than 5 minutes."

      # 높은 메모리 사용량
      - alert: UserServiceHighMemoryUsage
        expr: jvm_memory_used_bytes{job="user-service",area="heap"} / jvm_memory_max_bytes{job="user-service",area="heap"} > 0.85
        for: 10m
        labels:
          severity: warning
          service: user-service
        annotations:
          summary: "High memory usage in User Service"
          description: "User Service heap memory usage is above 85%."

      # 데이터베이스 연결 풀 임계치
      - alert: UserServiceHighDBConnections
        expr: hikaricp_connections_active{job="user-service"} / hikaricp_connections_max{job="user-service"} > 0.8
        for: 5m
        labels:
          severity: warning
          service: user-service
        annotations:
          summary: "High database connection usage"
          description: "User Service database connection pool is above 80% capacity."

      # JWT 토큰 검증 실패율
      - alert: UserServiceHighJWTFailureRate
        expr: rate(http_server_requests_total{job="user-service",uri=~"/api/v1/users/(login|refresh)",status=~"4.."}[5m]) / rate(http_server_requests_total{job="user-service",uri=~"/api/v1/users/(login|refresh)"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: user-service
        annotations:
          summary: "High JWT authentication failure rate"
          description: "User Service JWT authentication failure rate is above 10%."

      # 사용자 등록 실패율
      - alert: UserServiceHighSignupFailureRate
        expr: rate(http_server_requests_total{job="user-service",uri="/api/v1/users/signup",status=~"4..|5.."}[5m]) / rate(http_server_requests_total{job="user-service",uri="/api/v1/users/signup"}[5m]) > 0.05
        for: 10m
        labels:
          severity: warning
          service: user-service
        annotations:
          summary: "High user signup failure rate"
          description: "User signup failure rate is above 5%."