server:
  port: 9000

spring:
  application:
    name: api-gateway
  
  # ANSI 색상 출력 활성화
  output:
    ansi:
      enabled: always
    
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: ${CORS_ALLOWED_ORIGINS}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true
                maxAge: 3600
          routes:
            # User Service 라우팅
            - id: user-service
              uri: http://user-service:9001
              predicates:
                - Path=/api/v1/users/**
              filters:
                - name: AddRequestHeader
                  args:
                    name: X-Service-Name
                    value: user-service

            # Document Service 라우팅
            - id: document-service
              uri: http://document-service:9002
              predicates:
                - Path=/api/v1/documents/**
              filters:
                - name: AddRequestHeader
                  args:
                    name: X-Service-Name
                    value: document-service

  # Redis 설정 (Rate Limiting용)
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Actuator 설정 (헬스체크 및 메트릭) - 보안 강화 적용
# 관리 포트 분리로 외부 노출 차단
management:
  server:
    port: 9090  # 관리 전용 포트 (외부 노출 안함, 모니터링/헬스체크 전용)
  endpoints:
    web:
      exposure:
        include: 
          - health      # 서비스 헬스체크 (필수)
          - metrics     # 메트릭 수집 (모니터링용)
          - prometheus  # Prometheus 메트릭 (모니터링용)
          # info 엔드포인트 제거 - 버전 정보 노출 방지
          # gateway 엔드포인트 제거 - 라우팅 정보 노출 방지
  endpoint:
    health:
      show-details: never  # 상세 정보 완전 차단 (보안 강화)
      probes:
        enabled: true
  # info 엔드포인트 설정 제거 - 모든 빌드/Git 정보 노출 방지

# 로깅 설정
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: INFO
    me.helloc.techwikiplus.service.apigateway: DEBUG
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr([%-5level]){spring} %clr([%logger{36}]){cyan} - %clr(%msg){faint}%n"

# 서비스 정보
info:
  app:
    name: TechWikiPlus API Gateway
    description: Central API Gateway for TechWikiPlus services
    version: '@project.version@'
    profiles: ${spring.profiles.active:default}